"""add_category_to_recipes

Revision ID: 68962491080c
Revises: 8a15e963b5ad
Create Date: 2026-06-05 09:54:03.781294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68962491080c'
down_revision: Union[str, None] = '8a15e963b5ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('category', sa.String(length=20), nullable=False, server_default='recipe'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'category')
    # ### end Alembic commands ###
