"""add_gender_height_weight_to_users_and_meal_count_cheat_meal_to_weekly_plans

Revision ID: 8a15e963b5ad
Revises: 81cf08245b16
Create Date: 2026-06-04 19:42:47.566519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a15e963b5ad'
down_revision: Union[str, None] = '81cf08245b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('height_cm', sa.DECIMAL(precision=5, scale=1), nullable=True))
    op.add_column('users', sa.Column('weight_kg', sa.DECIMAL(precision=5, scale=1), nullable=True))
    op.add_column('weekly_plans', sa.Column('meal_count', sa.Integer(), nullable=False, server_default='3'))
    op.add_column('weekly_plans', sa.Column('cheat_meal', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_plans', 'cheat_meal')
    op.drop_column('weekly_plans', 'meal_count')
    op.drop_column('users', 'weight_kg')
    op.drop_column('users', 'height_cm')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
