"""initial: all tables

Revision ID: 940ab8c72fe5
Revises: 
Create Date: 2026-05-29 20:55:12.111197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940ab8c72fe5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard'), nullable=True),
    sa.Column('cooking_time_minutes', sa.Integer(), nullable=True),
    sa.Column('default_servings', sa.Integer(), nullable=True),
    sa.Column('total_calories', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('total_protein_grams', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('total_carbs_grams', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('total_fat_grams', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('total_fiber_grams', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('goal_type', sa.Enum('lose_fat', 'gain_muscle', 'maintain', name='goaltype'), nullable=False),
    sa.Column('daily_calories', sa.Integer(), nullable=False),
    sa.Column('daily_protein_grams', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('daily_carbs_grams', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('daily_fat_grams', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack'), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('servings', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('manual_name', sa.String(length=100), nullable=True),
    sa.Column('manual_grams', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('calories', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.Column('protein_grams', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('carbs_grams', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('fat_grams', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount_grams', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('substitute', sa.String(length=100), nullable=True),
    sa.Column('category', sa.Enum('meat', 'vegetable', 'staple', 'seasoning', 'other'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('total_grams', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('category', sa.Enum('meat', 'vegetable', 'staple', 'seasoning', 'other'), nullable=False),
    sa.Column('source_recipes', sa.JSON(), nullable=True),
    sa.Column('purchased', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack'), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('servings', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'plan_date', 'meal_type', name='uk_user_date_meal')
    )
    op.create_table('weight_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.DECIMAL(precision=4, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'record_date', name='uk_user_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weight_logs')
    op.drop_table('weekly_plans')
    op.drop_table('shopping_items')
    op.drop_table('recipe_steps')
    op.drop_table('recipe_ingredients')
    op.drop_table('daily_logs')
    op.drop_table('users')
    op.drop_table('recipes')
    # ### end Alembic commands ###
